export const options_changes = [
  'Missing caption requirements',
  'Inverted logo',
  'Incorrect brand name',
  'Audio not audible',
  'Video too dark',
  'Video too bright',
  'Mismatch of audio and video',
  'Frozen video',
  'Background too loud',
  'Voiceover not clear',
  'Audio not a good fit',
  'Audio too loud',
  'Spelling in subtitles',
]; 