version: '3.8'

services:
  cc-frontend:
    container_name: cc-frontend
    build:
      context: ./cc-frontend
      dockerfile: Dockerfile
      target: "development"
    ports:
      - "3030:3030"
    volumes:
      - ./cc-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
    networks:
      - cult-creative

  cc-backend:
    container_name: cc-backend
    build:
      target: development
      context: ./cc-backend
      dockerfile: Dockerfile
    env_file:
      - ./cc-backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./cc-backend:/app
      - /app/node_modules
    networks:
      - cult-creative
      # - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - cult-creative

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - cult-creative

networks:
  cult-creative:
    driver: bridge
  # db:
  #   name: database_database_db
  #   external: true