export const interestsLists = [
  'Art',
  'Automotive',
  'Beauty',
  'Education',
  'Entertainment',
  'F&B',
  'Family & Motherhood',
  'Fashion',
  'Finance & Business',
  'Gaming',
  'Health & Wellness',
  'Home & Living',
  'Lifestyle',
  'Music',
  'Sports & Fitness',
  'Tech',
  'Technology',
  'Travel',
];
