export const interestsLists = [
  'Art',
  'Automotive',
  'Banking & Finance',
  'Beauty & Skincare',
  'Business',
  'Education',
  'Entertainment',
  'Events',
  'F&B',
  'Fashion',
  'FMCG',
  'Gaming',
  'Health',
  'Home & Living',
  'Hotel & Travel',
  'Lifestyle',
  'Motherhood & Family',
  'Music',
  'Party',
  'Property',
  'Sports & Fitness',
  'Tech',
  'Technology',
  'Wellness',
  'Others',
];
